image:
  tag: latest
  repository_chat_frontend: registry/vlad.stetsenko/kubejam/chat_frontend
  pullPolicy: IfNotPresent

chat_frontend:
  name: chat-frontend
  replicaCount: 3
  wsInternalPort: 2000
  resources:
    limits:
      cpu: 0.1
      memory: 128Mi

redis:
  name: redis
  port: 6379
  resources:
    limits:
      cpu: 0.1
      memory: 128Mi

ingress:
  domain: example.com
  gateway:
    name: gatewayexample

config:
  version: v0.0.0


mongo:
  name: mongo-db
  port: 27017
  resources:
    limits:
      cpu: 0.1
      memory: 128Mi

