FROM python:3.6.7-slim as chat_frontend

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    g++ \
    make \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD ./requirements /app/requirements
ADD ./chat_frontend /app/chat_frontend

RUN pip3 install -r requirements/requirements.txt
