apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chat_frontend.name }}-service
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.chat_frontend.wsInternalPort }}
      protocol: TCP
      name: {{ .Values.chat_frontend.name }}-ws
  selector:
    app: {{ .Values.chat_frontend.name }}
